var Conference = require("./Conference");

/**
 * Creates a new Connection object. A Connection object represents the signalling (XMPP) connection
 * used by Jitsi Meet.
 * @param appID identification for the provider of Jitsi Meet video conferencing services.
 * @param token secret generated by the provider of Jitsi Meet video conferencing services.
 * The token will be send to the provider from the Jitsi Meet server deployment for authorization of the current client.
 * @param options Object with properties / settings related to connection with the server.
 * @constructor
 */
function Connection(appID, token, options) {

}

/**
 * Connects to the XMPP server.
 * @param successCallback this callback will be called if the connection is successful.
 * @param errorCallback this callback will be called if the connection fails.
 */
Connection.prototype.connect = function (successCallback, errorCallback) {

}

/**
 * Disconnects from the XMPP server.
 * @param successCallback this callback will be called if disconnect successfully.
 * @param errorCallback this callback will be called if the disconnect fails.
 */
Connection.prototype.disconnect = function (successCallback, errorCallback) {

}

/**
 * This method allows renewal of the tokens if they are expiring.
 * @param token the new token.
 */
Connection.prototype.setToken = function (token) {

}

/**
 * Creates a new Conference object.
 * @param name the name of the conference; if null - a generated name will be provided from the api
 * @param options Object with properties / settings related to the conference that will be created.
 * @returns {Conference} returns the new conference object.
 */
Connection.prototype.initConference = function (name, options) {
    return new Conference();
}

module.exports = Connection;